bindkey -v

zstyle :compinstall filename '/home/heynemann/.zshrc'

export PATH="~/.zsh/bin:$PATH"

if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

if [ -f "$HOME/.local.zsh" ]; then
  source "$HOME/.local.zsh" ]
fi

if [ -f "$HOME/.alias.zsh" ]; then
  source "$HOME/.alias.zsh" ]
fi

# General configs
source "$HOME/.zsh/includes/general.zsh"

# Plugins
source "$HOME/.zsh/includes/mise.zsh"
source "$HOME/.zsh/includes/plugins.zsh"
source "$HOME/.zsh/includes/starship.zsh"
